"""Gate-2 parity: the engine-accelerated BurstLoop vs the ORIGINAL genlm-control.

The reference is the genuine original genlm-control (main + llamppl ``smc_standard``)
-- the released per-token SMC the downstream (lvar) actually uses -- generated once
by ``gen_original_reference.py`` and cached in ``gate2_snapshot.json``. This test only
LOADS that cache and compares the engine-native ``BurstLoop`` against it. StepLoop is
NOT the reference here (it is the production fallback for non-burstable configs and
the ``accelerate="off"`` path, pinned == the original by gate-1's
``parity_snapshot.json``); disentangling the two is deliberate.

The burst and the original differ only in the source of next-token logits -- the
burst reads warm-KV decode logits inside vLLM rather than re-prefilling every step --
so they agree up to the warm-KV-vs-reprefill numerical residual (~1e-2/logit), which
may flip a single Gumbel-max draw but is small and unbiased. A consistent ``log_ml``
bias or systematically longer sequences in the burst is a BUG, not a tolerance.

**Reference cache.** The original reference is deterministic per
(target, N, ess, max_tokens, seed) and is the expensive half (per-token re-prefill).
Regenerate it (e.g. after changing configs / model) by running the ORIGINAL on the
box, shadowing our genlm.control with main's::

    PYTHONPATH=/root/genlm/genlm-control-main VLLM_USE_FLASHINFER_SAMPLER=0 \\
        OMP_NUM_THREADS=1 /root/genlm-venv/bin/python \\
        tests/sampler/gen_original_reference.py

A missing key is a hard error (run the generator) -- never a silent self-comparison.

Requires CUDA + vLLM; uses gpt2. Run on the box with
``VLLM_USE_FLASHINFER_SAMPLER=0 OMP_NUM_THREADS=1``.
"""

import asyncio
import json
import os
import time

import numpy as np
import pytest

torch = pytest.importorskip("torch")
if not torch.cuda.is_available():  # pragma: no cover
    pytest.skip("engine-native parity needs CUDA + vLLM", allow_module_level=True)

from genlm.control.constant import EndOfSequence  # noqa: E402
from genlm.control.potential import Potential  # noqa: E402
from genlm.control.potential.built_in.llm import PromptedLLM  # noqa: E402
from genlm.control.potential.built_in.wfsa import BoolFSA  # noqa: E402
from genlm.control.sampler.token import DirectTokenSampler, AWRS  # noqa: E402
from genlm.control.sampler.unit import (  # noqa: E402
    BoundaryPredicate,
    FixedLengthBoundary,
)
from genlm.control.sampler.controller import (  # noqa: E402
    Controller,
    BurstLoop,
    burst_capability,
)


def can_burst(controller):
    """Test-local ergonomics: the library exposes only ``burst_capability(...)``;
    this was a public wrapper, now lives here since only the tests want it."""
    return burst_capability(controller).ok


MODEL = "gpt2"
SEED = 1234
# Result-affecting global config shared by every gate-2 case (the constraint
# that DOES vary per case is encoded in each `label`). Recorded in the snapshot
# so a load against a mismatched reference fails loudly instead of silently
# comparing the burst against a stale slow run.
_EOS_BYTES = [b"\n"]
_PROMPT = "The"
_CONFIG = {"model": MODEL, "prompt": _PROMPT, "eos_hex": [b.hex() for b in _EOS_BYTES]}

# Original-reference snapshot (see module docstring): generated by
# ``gen_original_reference.py`` from the ORIGINAL genlm-control. This test only
# LOADS it; it never recomputes a slow run (no StepLoop reference here).
_SNAPSHOT_PATH = os.path.join(os.path.dirname(__file__), "gate2_snapshot.json")
try:
    with open(_SNAPSHOT_PATH) as _f:
        _SNAPSHOT = json.load(_f)
except FileNotFoundError:  # pragma: no cover
    _SNAPSHOT = {}

# `__config__` is metadata, not a reference entry -- pop it so it never collides
# with a data key lookup. A config mismatch means the reference was generated for a
# different model/prompt/eos, so the comparison would be meaningless.
_snap_config = _SNAPSHOT.pop("__config__", None)
if _snap_config is not None and _snap_config != _CONFIG:  # pragma: no cover
    raise RuntimeError(
        f"gate2_snapshot.json was generated under {_snap_config} but the tests "
        f"now run under {_CONFIG}; regenerate it with gen_original_reference.py."
    )


def _seed(s=SEED):
    np.random.seed(s)
    torch.manual_seed(s)


def _ctx_ids(ctx):
    """Token-id view of a particle context (EOS -> the sentinel string).

    A multi-token unit context nests units as sub-lists; flatten them so a unit
    run and a token run with the same tokens compare equal."""
    out = []

    def emit(t):
        if isinstance(t, EndOfSequence):
            out.append("EOS")
        elif isinstance(t, list):
            for s in t:
                emit(s)
        else:
            out.append(t.token_id)

    for t in ctx:
        emit(t)
    return out


def _controller(
    make_sampler, n_particles, ess_threshold, max_tokens, make_critic=None, slow_cadence=None
):
    # `make_sampler`/`make_critic` are factories so each burst run gets a fresh
    # sampler/critic (an AWRS carries its own RNG; a fresh one per run keeps it
    # seeded by `_seed` + its own seed). `twist_with_critic` mirrors SMC.__call__
    # exactly (per-step twist iff ess_threshold > 0). `slow_cadence` (the
    # inexpressible-step predicate) only affects the BurstLoop's lane choice.
    return Controller(
        unit_sampler=make_sampler(),
        critic=make_critic() if make_critic is not None else None,
        n_particles=n_particles,
        ess_threshold=ess_threshold,
        max_tokens=max_tokens,
        twist_with_critic=ess_threshold > 0,
        slow_cadence=slow_cadence,
    )


def _key(label, n_particles, ess_threshold, max_tokens, seed):
    return f"{label}|N={n_particles}|ess={ess_threshold}|mt={max_tokens}|seed={seed}"


def _ref(label, n_particles, ess_threshold, max_tokens, seed):
    """Load the cached ORIGINAL genlm-control reference for this config. A missing
    key is a hard error (run ``gen_original_reference.py`` on the box) rather than a
    silent self-comparison."""
    key = _key(label, n_particles, ess_threshold, max_tokens, seed)
    if key not in _SNAPSHOT:  # pragma: no cover
        raise RuntimeError(
            f"no cached original reference for {key!r}; regenerate with "
            "gen_original_reference.py (PYTHONPATH=.../genlm-control-main)"
        )
    return _SNAPSHOT[key]


def _run_burst(
    make_sampler, n_particles, ess_threshold, max_tokens, seed, make_critic=None, slow_cadence=None
):
    from genlm.control.sampler.sequence import Sequences, _unpack_particles

    _seed(seed)
    controller = _controller(
        make_sampler, n_particles, ess_threshold, max_tokens, make_critic, slow_cadence
    )
    driver = BurstLoop(controller)
    t0 = time.perf_counter()
    parts = asyncio.run(driver.run())
    dt = time.perf_counter() - t0
    seq = Sequences(*_unpack_particles(parts))
    return {
        "contexts": [_ctx_ids(p.context) for p in parts],
        "logw": [float(p.logw) for p in parts],
        "log_ml": float(seq.log_ml),
        "wall": dt,
        "n_bursts": driver.n_bursts,
        "n_slow_steps": driver.n_slow_steps,
    }


def _compare(label, ess_threshold, n_particles, ref, burst):
    """Burst-vs-cached-original stats + report. ``ref`` is the loaded original
    reference (``_ref``), ``burst`` the live engine-native run (``_run_burst``).
    Named ``slow``/``burst`` internally for the original report wording."""
    slow = ref
    slow_ctx, burst_ctx = slow["contexts"], burst["contexts"]
    slow_w = np.array(slow["logw"])
    burst_w = np.array(burst["logw"])

    n_match = sum(a == b for a, b in zip(slow_ctx, burst_ctx))
    slow_lens = [len(c) for c in slow_ctx]
    burst_lens = [len(c) for c in burst_ctx]
    # First-divergence step per particle: isolates single-flip-then-cascade
    # (the warm-KV signature) from a step-1 wiring bug.
    first_div = []
    for a, b in zip(slow_ctx, burst_ctx):
        k = next((i for i in range(min(len(a), len(b))) if a[i] != b[i]), None)
        first_div.append(k if k is not None else min(len(a), len(b)))

    matched = [
        abs(slow_w[i] - burst_w[i])
        for i in range(n_particles)
        if slow_ctx[i] == burst_ctx[i]
    ]
    signed = burst_w - slow_w
    finite = signed[np.isfinite(signed)]

    lines = [
        f"=== {label}  ess={ess_threshold}  N={n_particles} (slow cached) ===",
        f"contexts match: {n_match}/{n_particles}",
        f"first-divergence step per particle: {first_div}",
        f"mean len slow={np.mean(slow_lens):.3f} burst={np.mean(burst_lens):.3f}",
        f"max |logw diff| over matched contexts: "
        f"{max(matched) if matched else float('nan'):.4e}",
        f"signed logw diff (burst-slow): mean={np.mean(finite):+.4e} "
        f"std={np.std(finite):.4e} n={len(finite)}",
        f"slow log_ml={slow['log_ml']:.6f}  burst log_ml={burst['log_ml']:.6f}  "
        f"diff={burst['log_ml'] - slow['log_ml']:+.6f}",
        f"burst wall={burst['wall']:.2f}s  bursts opened={burst['n_bursts']}",
    ]
    print("\n" + "\n".join(lines))

    return {
        "n_bursts": burst["n_bursts"],
        "n_match": n_match,
        "log_ml_diff": float(burst["log_ml"] - slow["log_ml"]),
        "slow_log_ml": float(slow["log_ml"]),
        "burst_log_ml": float(burst["log_ml"]),
        "mean_len_slow": float(np.mean(slow_lens)),
        "mean_len_burst": float(np.mean(burst_lens)),
    }


@pytest.fixture(scope="module")
def llm():
    from genlm.backend.llm import AsyncVirtualLM

    model = AsyncVirtualLM.from_name(
        MODEL,
        engine_opts={
            "gpu_memory_utilization": 0.3,
            "max_model_len": 256,
            "enable_prefix_caching": True,
        },
    )
    return PromptedLLM(model, eos_byte_strings=_EOS_BYTES)


def _boolfsa_target(llm, regex):
    return llm * BoolFSA.from_regex(regex).coerce(llm, f=b"".join)


# ----- gate 2a: unconstrained ----------------------------------------------


@pytest.mark.parametrize("ess_threshold", [0.0, 0.5])
def test_unconstrained_burst_vs_slow(llm, ess_threshold):
    llm.set_prompt_from_str(_PROMPT)

    def make():
        return DirectTokenSampler(llm)

    assert can_burst(_controller(make, 8, ess_threshold, 12))
    slow = _ref("unconstrained", 8, ess_threshold, 12, SEED)
    burst = _run_burst(make, 8, ess_threshold, 12, SEED)
    stats = _compare("unconstrained", ess_threshold, 8, slow, burst)
    # Pure warm-KV residual (no factor): the burst draws from the same normalized
    # LM logw_next as the slow path, so length and log_ml track tightly.
    assert abs(stats["mean_len_burst"] - stats["mean_len_slow"]) <= 2.0, (
        f"length diverged (slow {stats['mean_len_slow']:.2f} vs "
        f"burst {stats['mean_len_burst']:.2f})"
    )
    assert abs(stats["log_ml_diff"]) <= 0.2, (
        f"log_ml diverged (slow {stats['slow_log_ml']:.4f} vs "
        f"burst {stats['burst_log_ml']:.4f})"
    )


# ----- gate 2b: constrained (additive factor folded into target) -----------


@pytest.mark.parametrize("ess_threshold", [0.0, 0.5])
def test_constrained_boolfsa_burst_vs_slow(llm, ess_threshold):
    llm.set_prompt_from_str(_PROMPT)
    target = _boolfsa_target(llm, r"[a-z ]+")

    def make():
        return DirectTokenSampler(target)

    assert can_burst(_controller(make, 16, ess_threshold, 12))
    slow = _ref("boolfsa[a-z ]+", 16, ess_threshold, 12, SEED)
    burst = _run_burst(make, 16, ess_threshold, 12, SEED)
    stats = _compare("boolfsa[a-z ]+", ess_threshold, 16, slow, burst)
    # Low-variance constrained case (broad allowed set, full-length sequences):
    # the warm-KV residual is small and unbiased, so a single-seed log_ml diff
    # and the mean length stay tight.
    assert abs(stats["mean_len_burst"] - stats["mean_len_slow"]) <= 2.0, (
        f"length diverged (slow {stats['mean_len_slow']:.2f} vs "
        f"burst {stats['mean_len_burst']:.2f})"
    )
    assert abs(stats["log_ml_diff"]) <= 0.2, (
        f"log_ml diverged (slow {stats['slow_log_ml']:.4f} vs "
        f"burst {stats['burst_log_ml']:.4f})"
    )


# ----- gate 2b': a tighter constraint that FORCES resampling (exercises the
#       burst pop-out / relaunch path, which the looser constraint does not) ---


def test_constrained_forces_resample_burst_vs_slow(llm):
    """Vowels+space only: sharply disagrees with the LLM, so per-step weights
    spread and ESS crosses 0.5 -> the burst must pop out, resample, and relaunch.

    This constraint narrows the proposal to ~53 tokens and produces very short
    sequences (~2-3 tokens), so a single run is high-variance Monte Carlo. We
    therefore (1) assert the pop-out/relaunch path actually ran (n_bursts > 1),
    and (2) check that the burst log_ml is UNBIASED by averaging the burst-vs-
    slow log_ml difference across several seeds -- the mean should sit near 0
    even though any single seed is noisy.
    """
    llm.set_prompt_from_str(_PROMPT)
    target = _boolfsa_target(llm, r"[aeiou ]+")

    def make():
        return DirectTokenSampler(target)

    seeds = (1234, 7, 99, 2024, 555, 31, 808, 42, 17, 6, 71, 900)
    diffs, len_gaps = [], []
    any_resample = False
    for seed in seeds:
        slow = _ref("boolfsa[aeiou ]+", 16, 0.5, 10, seed)
        burst = _run_burst(make, 16, 0.5, 10, seed)
        s = _compare("boolfsa[aeiou ]+", 0.5, 16, slow, burst)
        diffs.append(s["log_ml_diff"])
        len_gaps.append(s["mean_len_burst"] - s["mean_len_slow"])
        any_resample = any_resample or s["n_bursts"] > 1
    diffs = np.array(diffs)
    len_gaps = np.array(len_gaps)
    sem = diffs.std() / np.sqrt(len(diffs))
    print(f"\n[aeiou ]+ over {len(seeds)} seeds:")
    print(f"  log_ml diff mean={diffs.mean():+.4f} std={diffs.std():.4f} sem={sem:.4f}")
    print(f"  len gap mean={len_gaps.mean():+.3f}")

    assert any_resample, (
        "ESS never crossed across any seed -> the pop-out/relaunch path was "
        "not exercised; pick a tighter constraint"
    )
    # Unbiasedness is the testable claim: the MEAN log_ml diff and MEAN length gap
    # across seeds sit near 0. A persistent same-sign gap would be a real bias bug.
    assert abs(diffs.mean()) <= max(0.3, 2.0 * sem), (
        f"burst log_ml is biased across seeds: mean diff {diffs.mean():+.4f} "
        f"(sem {sem:.4f})"
    )
    assert abs(len_gaps.mean()) <= 1.5, (
        f"burst length is systematically biased: mean gap {len_gaps.mean():+.3f}"
    )


# ----- gate 2c: AWRS (rejection over engine logits + stateful condition) ------


def test_awrs_burst_vs_slow(llm):
    """AWRS over an engine LM + a boolean condition, in the burst: the rejection
    runs over the engine LM logits with the condition checked from its carried
    state (no per-step gather over the vocab). AWRS's weight is a Monte-Carlo
    estimate, so -- like the resample test -- check the burst-vs-slow log_ml is
    UNBIASED across seeds (mean near 0); a persistent same-sign gap would be a bug.
    """
    llm.set_prompt_from_str(_PROMPT)
    condition = BoolFSA.from_regex(r"[a-z ]+").coerce(llm, f=b"".join)

    def make_seed(s):
        # A fresh AWRS seeded per run so slow and burst share the rejection RNG,
        # and the seed varies the draws across the loop (AWRS uses its own RNG).
        def make():
            return AWRS(llm, condition, seed=s)

        return make

    assert can_burst(_controller(make_seed(SEED), 16, 0.0, 12))

    seeds = (1234, 7, 99, 2024, 555, 31)
    diffs, len_gaps = [], []
    for seed in seeds:
        make = make_seed(seed)
        slow = _ref("awrs[a-z ]+", 16, 0.0, 12, seed)
        burst = _run_burst(make, 16, 0.0, 12, seed)
        s = _compare("awrs[a-z ]+", 0.0, 16, slow, burst)
        diffs.append(s["log_ml_diff"])
        len_gaps.append(s["mean_len_burst"] - s["mean_len_slow"])
    diffs = np.array(diffs)
    len_gaps = np.array(len_gaps)
    sem = diffs.std() / np.sqrt(len(diffs))
    print(
        f"\nAWRS [a-z ]+ over {len(seeds)} seeds: "
        f"log_ml diff mean={diffs.mean():+.4f} sem={sem:.4f} "
        f"len gap mean={len_gaps.mean():+.3f}"
    )
    assert abs(diffs.mean()) <= max(0.3, 2.0 * sem), (
        f"AWRS burst log_ml biased: mean diff {diffs.mean():+.4f} (sem {sem:.4f})"
    )
    assert abs(len_gaps.mean()) <= 1.5, (
        f"AWRS burst length biased: mean gap {len_gaps.mean():+.3f}"
    )


# ----- gate 2d: critic (terminal reweight + per-step twist) -------------------
#
# The critic is NOT a sampler -- it reweights the population. The burst scores it
# via the SAME Controller._score_advance_terminate the slow loop uses (driven by
# run_sync from the engine-thread draw), so a terminal reweight (ess=0, the
# genlm-latent production regime) and a per-step twist (ess>0) are handled
# identically to the slow path. There is deliberately NO critic-category gate
# (is_terminal_only is not consulted): a critic is just a potential, scored the
# same way regardless of where the rollout logits came from.


class _TerminalContainsCritic(Potential):
    """Terminal 0/-inf indicator critic (the genlm-latent CoTCritic shape): the
    completed text must contain a space. ``prefix`` is 0 throughout; ``score``
    returns the indicator on any termination (EOS or budget cutoff)."""

    def __init__(self, vocab):
        super().__init__(vocabulary=vocab)

    async def _indicator(self, context):
        bs = [t for t in context if not isinstance(t, EndOfSequence)]
        try:
            text = b"".join(bs).decode("utf-8")
        except UnicodeDecodeError:
            return float("-inf")
        return 0.0 if " " in text else float("-inf")

    async def complete(self, context):
        return await self._indicator(context)

    async def prefix(self, context):
        return 0.0

    async def score(self, context):
        return await self._indicator(context)


class _SoftVowelCritic(Potential):
    """Soft, content-dependent critic: a -0.5 penalty per vowel in the decoded
    text. Finite and non-trivial (so a per-step twist accumulates real weight),
    and content-dependent (so particle weights diverge -> ESS drops -> the burst
    actually resamples, exercising the twist + pop-out interaction). The penalty
    is deliberately MODERATE: a stronger one (e.g. -1.0/vowel) collapses ESS to ~1
    effective particle every step, which maximizes variance without testing
    anything more and leaves the parity check unable to distinguish bias from
    noise. Deterministic in the context."""

    def __init__(self, vocab):
        super().__init__(vocabulary=vocab)

    def _pen(self, context):
        bs = [t for t in context if not isinstance(t, EndOfSequence)]
        try:
            text = b"".join(bs).decode("utf-8")
        except UnicodeDecodeError:
            return float("-inf")
        return -0.5 * sum(c in "aeiouAEIOU" for c in text)

    async def complete(self, context):
        return self._pen(context)

    async def prefix(self, context):
        return self._pen(context)


def test_terminal_critic_burst_vs_slow(llm):
    """DirectTokenSampler(llm) + a terminal indicator critic at ess=0 -- the
    genlm-latent production regime: rollouts drawn from the backend, the indicator
    applied once at termination (run_sync). No resampling (ess=0); the burst-vs-
    slow log_ml must be unbiased across seeds."""
    llm.set_prompt_from_str(_PROMPT)

    def make():
        return DirectTokenSampler(llm)

    def make_critic():
        return _TerminalContainsCritic(llm.vocab)

    assert can_burst(_controller(make, 16, 0.0, 12, make_critic))

    seeds = (1234, 7, 99, 2024, 555, 31)
    diffs = []
    for seed in seeds:
        slow = _ref("terminal-critic", 16, 0.0, 12, seed)
        burst = _run_burst(make, 16, 0.0, 12, seed, make_critic)
        s = _compare("terminal-critic", 0.0, 16, slow, burst)
        diffs.append(s["log_ml_diff"])
    diffs = np.array(diffs)
    sem = diffs.std() / np.sqrt(len(diffs))
    print(
        f"\nterminal critic over {len(seeds)} seeds: "
        f"log_ml diff mean={diffs.mean():+.4f} sem={sem:.4f}"
    )
    assert abs(diffs.mean()) <= max(0.3, 2.0 * sem), (
        f"terminal-critic burst log_ml biased: mean {diffs.mean():+.4f} (sem {sem:.4f})"
    )


def test_twisting_critic_burst_vs_slow(llm):
    """DirectTokenSampler(llm) + a soft content-dependent critic at ess=0.5 -- the
    per-step twist regime. Exercises untwist/twist accumulation and ESS resampling
    on TWISTED weights inside the burst. Asserts the resample path ran (n_bursts>1)
    and the burst-vs-slow log_ml + length are unbiased across seeds."""
    llm.set_prompt_from_str(_PROMPT)

    def make():
        return DirectTokenSampler(llm)

    def make_critic():
        return _SoftVowelCritic(llm.vocab)

    assert can_burst(_controller(make, 16, 0.5, 12, make_critic))

    # Many seeds so the unbiasedness check has discriminating power (the warm-KV
    # residual makes each run noisy; bias must show as a mean many sem from 0).
    seeds = (1234, 7, 99, 2024, 555, 31, 8, 17, 42, 123, 271, 314)
    diffs, len_gaps, any_resample = [], [], False
    for seed in seeds:
        slow = _ref("twist-critic", 16, 0.5, 12, seed)
        burst = _run_burst(make, 16, 0.5, 12, seed, make_critic)
        s = _compare("twist-critic", 0.5, 16, slow, burst)
        diffs.append(s["log_ml_diff"])
        len_gaps.append(s["mean_len_burst"] - s["mean_len_slow"])
        any_resample = any_resample or s["n_bursts"] > 1
    diffs = np.array(diffs)
    len_gaps = np.array(len_gaps)
    ml_sem = diffs.std() / np.sqrt(len(diffs))
    len_sem = len_gaps.std() / np.sqrt(len(len_gaps))
    print(
        f"\ntwist critic over {len(seeds)} seeds: "
        f"log_ml diff mean={diffs.mean():+.4f} sem={ml_sem:.4f} | "
        f"len gap mean={len_gaps.mean():+.3f} sem={len_sem:.3f}"
    )
    assert any_resample, "twist-critic ess=0.5 never resampled; pop-out path unexercised"
    # Both checks are sem-aware: unbiased means the mean sits within sampling
    # noise of 0. A persistent same-sign gap many sem from 0 is the bug.
    assert abs(diffs.mean()) <= max(0.3, 2.5 * ml_sem), (
        f"twist-critic burst log_ml biased: mean {diffs.mean():+.4f} (sem {ml_sem:.4f})"
    )
    assert abs(len_gaps.mean()) <= max(0.5, 2.5 * len_sem), (
        f"twist-critic burst length biased: mean gap {len_gaps.mean():+.3f} "
        f"(sem {len_sem:.3f})"
    )


# ----- gate 2f: MultiTokenUnitSampler (synchronized unit-grain burst) ---------
#
# The unit grain is the one NON-free-running burst: a unit spans a VARIABLE number
# of subunit decode steps, so rows reach their unit boundary at different engine
# steps. Each row pops out and waits at its boundary; the controller runs exactly
# ONE unit round per burst and tests ESS once at the synced boundary -- the slow
# per-unit loop's timing. The byte-length boundary below makes units variable-
# length (Token is a bytes subclass), so the staggered pop-out is actually exercised
# (a fixed-length boundary would complete every row at the same step and hide it).


class _ByteLengthBoundary(BoundaryPredicate):
    """A unit completes once its subunits span >= ``min_bytes`` bytes. Content-
    dependent and variable-length -> rows reach the boundary at different engine
    steps -> the staggered per-unit pop-out the burst must sync."""

    def __init__(self, min_bytes):
        self.min_bytes = min_bytes

    def __call__(self, unit_context, subunit_buffer):
        return (
            sum(len(t) for t in subunit_buffer if not isinstance(t, EndOfSequence))
            >= self.min_bytes
        )


def test_multitoken_burst_vs_slow(llm):
    """MultiToken with a CONSTRAINED Direct subunit (``llm * coerced BoolFSA``) in
    the burst at ess=0.5: subunits ride the warm-KV fast lane with the boolfsa
    factor advancing per subunit; a unit completes at a byte-length boundary
    (variable length -> staggered pop-out, rows finishing their unit at different
    engine steps); and ESS fires once per unit round at the synced boundary -- the
    slow per-unit loop's timing.

    The constraint makes per-step weights NON-TRIVIAL (log_ml != 0, unlike the
    unconstrained Direct whose proposal is its own target and whose weights are all
    ~0), so the burst-vs-slow log_ml comparison actually tests the per-unit weight
    accumulation + ESS + resample. This is a NO-BIAS check, not byte-parity: the slow
    ``asyncio.gather`` consumes the numpy RNG in a different order than the burst's
    sequential per-row loop, so the draws diverge from the first subunit (contexts
    match ~0) -- a mis-timed ESS / double-counted unit weight would show as a
    SYSTEMATIC log_ml shift across seeds, which the many-seed mean catches.
    ``n_bursts`` counts unit ROUNDS (one burst each), confirming the synchronized
    per-unit loop ran."""
    from genlm.control.sampler.unit import MultiTokenUnitSampler

    llm.set_prompt_from_str(_PROMPT)
    target = _boolfsa_target(llm, r"[a-z ]+")

    def make():
        return MultiTokenUnitSampler(
            DirectTokenSampler(target),
            _ByteLengthBoundary(5),
            max_subunits_per_unit=6,
        )

    assert can_burst(_controller(make, 8, 0.5, 6))  # rides the fast lane

    # Many seeds: the no-bias check needs discriminating power (each run is noisy;
    # a real bias must show as a mean many sem from 0).
    seeds = (1234, 7, 99, 2024, 555, 31, 8, 17, 42, 123, 271, 314)
    diffs, len_gaps = [], []
    n_rounds = 0
    for seed in seeds:
        slow = _ref("multitoken-boolfsa[a-z ]+", 8, 0.5, 6, seed)
        burst = _run_burst(make, 8, 0.5, 6, seed)
        s = _compare("multitoken-boolfsa[a-z ]+", 0.5, 8, slow, burst)
        diffs.append(s["log_ml_diff"])
        len_gaps.append(s["mean_len_burst"] - s["mean_len_slow"])
        n_rounds = max(n_rounds, s["n_bursts"])
    diffs = np.array(diffs)
    len_gaps = np.array(len_gaps)
    ml_sem = diffs.std() / np.sqrt(len(diffs))
    len_sem = len_gaps.std() / np.sqrt(len(len_gaps))
    print(
        f"\nmultitoken boolfsa[a-z ]+ over {len(seeds)} seeds: "
        f"log_ml diff mean={diffs.mean():+.4f} sem={ml_sem:.4f} | "
        f"len gap mean={len_gaps.mean():+.3f} sem={len_sem:.3f}"
    )
    assert n_rounds > 1, (
        "multitoken burst ran a single unit round -> the synchronized per-unit "
        "loop (one burst per unit) was not exercised"
    )
    assert abs(diffs.mean()) <= max(0.3, 2.5 * ml_sem), (
        f"multitoken burst log_ml biased: mean {diffs.mean():+.4f} (sem {ml_sem:.4f})"
    )
    assert abs(len_gaps.mean()) <= max(0.5, 2.5 * len_sem), (
        f"multitoken burst length biased: mean gap {len_gaps.mean():+.3f} "
        f"(sem {len_sem:.3f})"
    )


# ----- gate 2g: slow-lane interleave (inexpressible-step cadence -> slow lane) ----
#
# 2d: with a `slow_cadence`, the driver bursts the expressible runs and drops to the
# exact per-token transition for the cadence steps (engine free), re-entering after
# each -- the mechanism for a periodic second/larger critic-LM forward that must not
# run inside the decode loop. The cadence is a PERFORMANCE hint: the per-step math is
# identical on both lanes, so the interleaved result is unchanged. The test pins that
# against the cached ORIGINAL (a plain constrained run, no cadence): a burst with
# every 3rd token forced to the slow lane must match the original's distribution
# (no systematic log_ml/length shift -- only the warm-KV residual), AND the slow lane
# must actually have run (n_slow_steps > 0).


def test_slow_lane_cadence_neutral(llm):
    """Slow-lane interleave (2d) is math-neutral. A constrained Direct config
    (non-trivial log_ml) is run as a burst whose ``slow_cadence`` is a
    ``FixedLengthBoundary(2)`` -- the same boundary library the unit sampler uses,
    reused as the cadence: 2 tokens burst, the 3rd drops to the per-token slow lane,
    repeat. It is compared to the cached ORIGINAL genlm-control run of the SAME
    config WITHOUT any cadence. They must agree in log_ml + length across seeds (the
    cadence only moves where work runs, not the distribution), and the slow lane must
    actually have run (n_slow_steps > 0)."""
    llm.set_prompt_from_str(_PROMPT)
    target = _boolfsa_target(llm, r"[a-z ]+")

    def make():
        return DirectTokenSampler(target)

    # FixedLengthBoundary(2): a run of 2 burst tokens fires the boundary, so every
    # 3rd token runs on the slow lane (the predicate sees the run buffer, not the
    # whole context, and re-arms after each slow step).
    cadence = FixedLengthBoundary(2)

    seeds = (1234, 7, 99, 2024, 555, 31)
    diffs, len_gaps, ran_slow = [], [], True
    for seed in seeds:
        orig = _ref("slowcadence-base[a-z ]+", 16, 0.5, 12, seed)
        inter = _run_burst(make, 16, 0.5, 12, seed, slow_cadence=cadence)
        s = _compare("slowcadence[a-z ]+", 0.5, 16, orig, inter)
        diffs.append(s["log_ml_diff"])
        len_gaps.append(s["mean_len_burst"] - s["mean_len_slow"])
        ran_slow = ran_slow and inter["n_slow_steps"] > 0
    diffs = np.array(diffs)
    len_gaps = np.array(len_gaps)
    ml_sem = diffs.std() / np.sqrt(len(diffs))
    len_sem = len_gaps.std() / np.sqrt(len(len_gaps))
    print(
        f"\nslow-lane cadence (every 3rd tok) vs ORIGINAL over {len(seeds)} seeds: "
        f"log_ml diff mean={diffs.mean():+.4f} sem={ml_sem:.4f} | "
        f"len gap mean={len_gaps.mean():+.3f} sem={len_sem:.3f}"
    )
    assert ran_slow, (
        "the cadence never popped to the slow lane (n_slow_steps == 0) -> the "
        "slow-lane handoff was not exercised"
    )
    assert abs(diffs.mean()) <= max(0.3, 2.5 * ml_sem), (
        f"slow-lane interleave shifts log_ml vs original: mean {diffs.mean():+.4f} "
        f"(sem {ml_sem:.4f})"
    )
    assert abs(len_gaps.mean()) <= max(0.5, 2.5 * len_sem), (
        f"slow-lane interleave shifts length vs original: mean gap "
        f"{len_gaps.mean():+.3f} (sem {len_sem:.3f})"
    )


# ----- gate 2e: SetTokenSampler (trie set construction over warm-KV iter weights) ----


def test_set_sampler_burst_vs_slow(llm):
    """SetTokenSampler over an EagerSetSampler(iter=engine LM, item=byte FSA), in
    the burst: the trie set construction runs over the engine's warm-KV iterable
    weights (sample_set's iter_logws), the item potential replays from context
    control-side -- exactly the slow path with only the iterable weights
    substituted. Unbiased log_ml across seeds (the warm-KV residual only perturbs
    the iterable weights). Small N/max_tokens because the trie set draw is
    expensive."""
    from genlm.control.sampler import EagerSetSampler
    from genlm.control.sampler.token import SetTokenSampler

    llm.set_prompt_from_str(_PROMPT)
    item = BoolFSA.from_regex(r"[a-z ]+")
    # Build the trie set sampler ONCE (heavy init over the LM vocab) and reuse it
    # across seeds -- it carries no per-run RNG (the draw uses the global stream
    # that `_seed` controls).
    set_sampler = EagerSetSampler(iter_potential=llm, item_potential=item)

    def make():
        return SetTokenSampler(set_sampler)

    try:
        # Decision 2 (UX): the Set sampler's in-engine path exists and is correct
        # (the burst-vs-slow parity below proves it) but is reported as NOT
        # accelerated -- the capability gate routes it to StepLoop. The numerical
        # parity check still drives BurstLoop directly via `_run_burst`.
        assert not can_burst(_controller(make, 8, 0.0, 8))
        cap = burst_capability(_controller(make, 8, 0.0, 8))
        assert cap.reason == "SetTokenSampler is not engine-accelerated"
        seeds = (1234, 7, 99, 2024, 555, 31)
        diffs = []
        for seed in seeds:
            slow = _ref("set[a-z ]+", 8, 0.0, 8, seed)
            burst = _run_burst(make, 8, 0.0, 8, seed)
            s = _compare("set[a-z ]+", 0.0, 8, slow, burst)
            diffs.append(s["log_ml_diff"])
        diffs = np.array(diffs)
        sem = diffs.std() / np.sqrt(len(diffs))
        print(
            f"\nset sampler over {len(seeds)} seeds: "
            f"log_ml diff mean={diffs.mean():+.4f} sem={sem:.4f}"
        )
        assert abs(diffs.mean()) <= max(0.3, 2.5 * sem), (
            f"set-sampler burst log_ml biased: mean {diffs.mean():+.4f} (sem {sem:.4f})"
        )
    finally:
        asyncio.run(set_sampler.cleanup())
