"""Gate-2 parity: the engine-accelerated BurstLoop is UNBIASED vs the exact per-token path.

Byte-exactness is impossible here -- the burst reads warm-KV decode logits inside vLLM
instead of re-prefilling every step, a ~1e-2/logit residual that may flip a Gumbel-max
draw -- so each test averages the burst-vs-reference log_ml (and length) diff across seeds
and asserts the MEAN sits within sampling noise of 0 (``_harness.assert_unbiased``). A
consistent same-sign gap is a BUG, not a tolerance.

Two references, chosen per case (the ``reference`` field of ``gate2_cases.CASES``):
- ``"ref"`` -- the genuine ORIGINAL genlm-control (main + llamppl ``smc_standard``), cached
  in ``gate2_snapshot.json`` by ``gen_original_reference.py`` and loaded via ``_ref``. The
  strongest anchor (independent of our StepLoop); used wherever a cached key exists.
- ``"steploop"`` -- a live ``accelerate="off"`` StepLoop at the same seed (``_run_steploop``),
  for configs with no cached original (multi-view, multitoken-multiview, batched). This is
  RNG-matched, so the paired diff is tight.

Config (seeds/N/ess/critics/samplers) and the shared critics live in ``gate2_cases.py``,
imported by BOTH this gate and the generator so they cannot drift; the seed/serialization/
no-bias-assert harness is ``_harness.py`` (shared with gate-1).

**Regenerate the cached original** (after changing a ``"ref"`` config) on the box, shadowing
our genlm.control with main's::

    PYTHONPATH=/root/genlm/genlm-control-main VLLM_USE_FLASHINFER_SAMPLER=0 \\
        /root/genlm-venv/bin/python tests/sampler/gen_original_reference.py

A missing key is a hard error (run the generator) -- never a silent self-comparison.

Requires CUDA + vLLM; uses gpt2. Run on the box with ``VLLM_USE_FLASHINFER_SAMPLER=0``.
"""

import asyncio
import os
import time

import numpy as np
import pytest

torch = pytest.importorskip("torch")
if not torch.cuda.is_available():  # pragma: no cover
    pytest.skip("engine-native parity needs CUDA + vLLM", allow_module_level=True)

from genlm.control.potential.built_in.llm import PromptedLLM  # noqa: E402
from genlm.control.sampler.token import DirectTokenSampler  # noqa: E402
from genlm.control.sampler.unit import MultiTokenUnitSampler  # noqa: E402
from genlm.control.sampler.smc import Controller, StepLoop  # noqa: E402
from genlm.control.sampler.burst import BurstLoop, burst_blocker  # noqa: E402

from _harness import seed_all, ctx_ids, load_snapshot, assert_unbiased  # noqa: E402
from gate2_cases import (  # noqa: E402
    CASES,
    MODEL,
    PROMPT,
    EOS_BYTES,
    CONFIG,
    ByteLengthBoundary,
    boolfsa,
)
from genlm.control.util import set_draw_method  # noqa: E402


@pytest.fixture(scope="module", autouse=True)
def _threefry_draw():
    """Gate-2 RNG-matches burst<->StepLoop via the counter-based picker (device-agnostic),
    so each comparison is a tight paired check (warm-KV residual only) instead of
    divergent-path MC noise. Scoped + restored so it can't leak into gate-1 (whose llamppl
    reference can't set draw keys, so it must stay gumbel_max)."""
    set_draw_method("threefry_gumbel")
    yield
    set_draw_method("gumbel_max")


_T0 = time.perf_counter()


def _log(msg):
    """Flushed, timestamped progress line. Streams live under ``pytest -s`` so a long
    gate-2 run shows constant progress (per-run wall, bursts) instead of going dark."""
    print(f"[{time.perf_counter() - _T0:7.1f}s] {msg}", flush=True)


def can_burst(controller):
    """Test-local: can this config run the engine burst (no blocker reason)?"""
    return burst_blocker(controller) is None


SEED = 1234  # single-seed default (unconstrained); per-case seeds come from CASES

# Original-reference snapshot (model/prompt/eos in CONFIG, enforced on load). Generated by
# ``gen_original_reference.py`` from the ORIGINAL genlm-control; this gate only LOADS it.
_SNAPSHOT_PATH = os.path.join(os.path.dirname(__file__), "gate2_snapshot.json")
try:
    _SNAPSHOT = load_snapshot(_SNAPSHOT_PATH, CONFIG)
except FileNotFoundError:  # pragma: no cover
    _SNAPSHOT = {}

# Tight reference: cached OUR-StepLoop+threefry (RNG-matched to the burst), generated by
# ``gen_steploop_reference.py``. SEPARATE file from the original ``_SNAPSHOT`` above.
_STEPLOOP_PATH = os.path.join(os.path.dirname(__file__), "gate2_steploop_snapshot.json")
try:
    _STEPLOOP_SNAP = load_snapshot(_STEPLOOP_PATH, CONFIG)
except FileNotFoundError:  # pragma: no cover
    _STEPLOOP_SNAP = {}


def _controller(make_sampler, n_particles, ess_threshold, max_tokens, make_critic=None):
    # `make_sampler`/`make_critic` are factories so each burst run gets a fresh
    # sampler/critic (an AWRS carries its own RNG; a fresh one per run keeps it
    # seeded by `seed_all` + its own seed). `twist_with_critic` mirrors SMC.__call__
    # exactly (per-step twist iff ess_threshold > 0).
    return Controller(
        unit_sampler=make_sampler(),
        critic=make_critic() if make_critic is not None else None,
        n_particles=n_particles,
        ess_threshold=ess_threshold,
        max_tokens=max_tokens,
        twist_with_critic=ess_threshold > 0,
    )


def _key(label, n_particles, ess_threshold, max_tokens, seed):
    return f"{label}|N={n_particles}|ess={ess_threshold}|mt={max_tokens}|seed={seed}"


def _ref(label, n_particles, ess_threshold, max_tokens, seed):
    """Load the cached ORIGINAL genlm-control reference for this config. A missing
    key is a hard error (run ``gen_original_reference.py`` on the box) rather than a
    silent self-comparison."""
    key = _key(label, n_particles, ess_threshold, max_tokens, seed)
    if key not in _SNAPSHOT:  # pragma: no cover
        raise RuntimeError(
            f"no cached original reference for {key!r}; regenerate with "
            "gen_original_reference.py (PYTHONPATH=.../genlm-control-main)"
        )
    return _SNAPSHOT[key]


def _steploop_cached(label, n_particles, ess_threshold, max_tokens, seed):
    """Load the cached OUR-StepLoop+threefry (tight, RNG-matched) reference. A missing key
    is a hard error -- run ``gen_steploop_reference.py`` on the box."""
    key = _key(label, n_particles, ess_threshold, max_tokens, seed)
    if key not in _STEPLOOP_SNAP:  # pragma: no cover
        raise RuntimeError(
            f"no cached StepLoop+threefry reference for {key!r}; regenerate with "
            "gen_steploop_reference.py"
        )
    return _STEPLOOP_SNAP[key]


def _run_burst(
    make_sampler, n_particles, ess_threshold, max_tokens, seed, make_critic=None
):
    from genlm.control.sampler.sequence import Sequences, _unpack_particles

    seed_all(seed)
    controller = _controller(
        make_sampler, n_particles, ess_threshold, max_tokens, make_critic
    )
    driver = BurstLoop(controller)
    t0 = time.perf_counter()
    parts = asyncio.run(driver.run())
    dt = time.perf_counter() - t0
    seq = Sequences(*_unpack_particles(parts))
    return {
        "contexts": [ctx_ids(p.context) for p in parts],
        "logw": [float(p.logw) for p in parts],
        "log_ml": float(seq.log_ml),
        "wall": dt,
        "n_bursts": driver.n_bursts,
        "n_resamples": controller.n_resamples,
    }


def _run_steploop(
    make_sampler, n_particles, ess_threshold, max_tokens, seed, make_critic=None
):
    """Same as ``_run_burst`` but the byte-exact StepLoop (``accelerate="off"``
    ground truth, gate-1-pinned == original) -- the reference for configs with no
    cached original snapshot (e.g. multi-view proposal)."""
    from genlm.control.sampler.sequence import Sequences, _unpack_particles

    seed_all(seed)
    controller = _controller(
        make_sampler, n_particles, ess_threshold, max_tokens, make_critic
    )
    parts = asyncio.run(StepLoop(controller).run())
    seq = Sequences(*_unpack_particles(parts))
    return {
        "contexts": [ctx_ids(p.context) for p in parts],
        "logw": [float(p.logw) for p in parts],
        "log_ml": float(seq.log_ml),
        "wall": 0.0,
        "n_bursts": 0,
        "n_resamples": controller.n_resamples,
    }


def _compare(label, ess_threshold, n_particles, ref, burst):
    """Burst-vs-cached-original stats + report. ``ref`` is the loaded original
    reference (``_ref``), ``burst`` the live engine-native run (``_run_burst``).
    Named ``slow``/``burst`` internally for the original report wording."""
    _log(
        f"{label} ess={ess_threshold} N={n_particles}: wall={burst['wall']:.1f}s "
        f"bursts={burst['n_bursts']} resamples={burst['n_resamples']} log_ml={burst['log_ml']:.3f}"
    )
    slow = ref
    slow_ctx, burst_ctx = slow["contexts"], burst["contexts"]
    slow_w = np.array(slow["logw"])
    burst_w = np.array(burst["logw"])

    n_match = sum(a == b for a, b in zip(slow_ctx, burst_ctx))
    slow_lens = [len(c) for c in slow_ctx]
    burst_lens = [len(c) for c in burst_ctx]
    # First-divergence step per particle: isolates single-flip-then-cascade
    # (the warm-KV signature) from a step-1 wiring bug.
    first_div = []
    for a, b in zip(slow_ctx, burst_ctx):
        k = next((i for i in range(min(len(a), len(b))) if a[i] != b[i]), None)
        first_div.append(k if k is not None else min(len(a), len(b)))

    matched = [
        abs(slow_w[i] - burst_w[i])
        for i in range(n_particles)
        if slow_ctx[i] == burst_ctx[i]
    ]
    signed = burst_w - slow_w
    finite = signed[np.isfinite(signed)]

    lines = [
        f"=== {label}  ess={ess_threshold}  N={n_particles} (slow cached) ===",
        f"contexts match: {n_match}/{n_particles}",
        f"first-divergence step per particle: {first_div}",
        f"mean len slow={np.mean(slow_lens):.3f} burst={np.mean(burst_lens):.3f}",
        f"max |logw diff| over matched contexts: "
        f"{max(matched) if matched else float('nan'):.4e}",
        f"signed logw diff (burst-slow): mean={np.mean(finite):+.4e} "
        f"std={np.std(finite):.4e} n={len(finite)}",
        f"slow log_ml={slow['log_ml']:.6f}  burst log_ml={burst['log_ml']:.6f}  "
        f"diff={burst['log_ml'] - slow['log_ml']:+.6f}",
        f"burst wall={burst['wall']:.2f}s  bursts opened={burst['n_bursts']}",
    ]
    print("\n" + "\n".join(lines))

    return {
        "n_bursts": burst["n_bursts"],
        "n_resamples": burst["n_resamples"],
        "n_match": n_match,
        "log_ml_diff": float(burst["log_ml"] - slow["log_ml"]),
        "slow_log_ml": float(slow["log_ml"]),
        "burst_log_ml": float(burst["log_ml"]),
        "mean_len_slow": float(np.mean(slow_lens)),
        "mean_len_burst": float(np.mean(burst_lens)),
    }


@pytest.fixture(scope="module")
def llm():
    from genlm.backend.llm import AsyncVirtualLM

    # Under xdist, stagger engine init by worker so simultaneous vLLM memory-profiles
    # don't race for GPU memory (each worker reserves gpu_memory_utilization on its own).
    wid = os.environ.get("PYTEST_XDIST_WORKER")
    if wid:
        time.sleep(int(wid[2:]) * 10)
    _log(f"loading {MODEL} vLLM engine ...")
    t0 = time.perf_counter()
    model = AsyncVirtualLM.from_name(
        MODEL,
        engine_opts={
            "gpu_memory_utilization": 0.2,
            "max_model_len": 256,
            "enable_prefix_caching": True,
            "enforce_eager": True,  # skip CUDA-graph capture -> faster startup for tests
        },
    )
    _log(f"engine ready in {time.perf_counter() - t0:.1f}s")
    return PromptedLLM(model, eos_byte_strings=EOS_BYTES)


def _nobias(label, llm, *, ml_floor=0.3, ml_k=2.5, len_bound=None, len_k=None,
            need_resample=False, need_rounds=False):
    """Drive a homogeneous CASES no-bias case and assert the burst is unbiased.

    Per seed: burst vs reference (cached original ``_ref`` or live StepLoop, per
    ``case.reference``), accumulate the log_ml + length diffs, then assert the MEAN
    log_ml diff is within sampling noise of 0 (``assert_unbiased``). ``len_bound``
    bounds the mean length gap (sem-aware if ``len_k`` given, else absolute).
    ``need_resample`` / ``need_rounds`` guard that the resample / per-unit-round path
    actually fired (no vacuous pass); a ``n_bursts>0`` guard always runs."""
    c = CASES[label]
    llm.set_prompt_from_str(PROMPT)
    mkc = (lambda: c.critic(llm)) if c.make_critic is not None else None
    assert can_burst(
        _controller(lambda: c.sampler(llm, c.seeds[0]), c.n_particles, c.ess, c.max_tokens, mkc)
    )
    diffs, len_gaps = [], []
    any_resample, max_bursts = False, 0
    for seed in c.seeds:
        make = lambda s=seed: c.sampler(llm, s)  # noqa: E731
        if c.reference == "ref":
            slow = _ref(c.label, c.n_particles, c.ess, c.max_tokens, seed)
        elif c.reference == "steploop_cached":
            slow = _steploop_cached(c.label, c.n_particles, c.ess, c.max_tokens, seed)
        else:
            slow = _run_steploop(make, c.n_particles, c.ess, c.max_tokens, seed, mkc)
        burst = _run_burst(make, c.n_particles, c.ess, c.max_tokens, seed, mkc)
        s = _compare(c.label, c.ess, c.n_particles, slow, burst)
        diffs.append(s["log_ml_diff"])
        len_gaps.append(s["mean_len_burst"] - s["mean_len_slow"])
        any_resample = any_resample or s["n_resamples"] > 0
        max_bursts = max(max_bursts, s["n_bursts"])
    assert max_bursts > 0, f"{c.label}: burst never opened (n_bursts==0)"
    if need_resample:
        assert any_resample, f"{c.label}: ESS never crossed -- resample path unexercised"
    if need_rounds:
        assert max_bursts > 1, f"{c.label}: single unit round -- per-unit loop unexercised"
    m, sem = assert_unbiased(diffs, floor=ml_floor, k=ml_k, label=f"{c.label} log_ml")
    _log(f"{c.label}: log_ml diff mean={m:+.4f} sem={sem:.4f}")
    if len_bound is not None:
        if len_k is None:
            lg = np.asarray(len_gaps, float)
            assert abs(lg.mean()) <= len_bound, (
                f"{c.label}: length biased -- mean gap {lg.mean():+.3f} > {len_bound}"
            )
        else:
            assert_unbiased(len_gaps, floor=len_bound, k=len_k, label=f"{c.label} length")
    return np.array(diffs), np.array(len_gaps)


# ----- gate 2a: unconstrained (no-bias over seeds; the force-EOS boundary weight +
#       bf16 draw flips make a single-seed tight check invalid) ----------------------


def test_unconstrained_burst_vs_slow(llm):
    _nobias("unconstrained", llm, ml_floor=0.3, ml_k=2.5, len_bound=1.5)


# ----- gate 2b: constrained Direct (llm * boolfsa). Looser [a-z ]+ at ess=0 (no
#       resample, vs StepLoop); tighter [aeiou ]+ at ess=0.5 FORCES the pop-out /
#       relaunch resample path (vs cached original). --


def test_constrained_boolfsa_burst_vs_slow(llm):
    _nobias("constrained-boolfsa[a-z ]+", llm, ml_floor=0.3, ml_k=2.5, len_bound=1.5)


def test_constrained_forces_resample_burst_vs_slow(llm):
    _nobias("boolfsa[aeiou ]+", llm, ml_floor=0.3, ml_k=2.0, len_bound=1.5, need_resample=True)


# ----- gate 2c: AWRS (rejection over engine logits + stateful condition; per-seed rng) --


def test_awrs_burst_vs_slow(llm):
    _nobias("awrs[a-z ]+", llm, ml_floor=0.3, ml_k=2.0, len_bound=1.5)


# ----- gate 2d: critic (terminal reweight + per-step twist) -------------------
#
# The critic is NOT a sampler -- it reweights the population. The burst scores it
# via the SAME Controller._bank_step the slow loop uses (driven by
# run_sync from the engine-thread draw), so a terminal reweight (ess=0, the
# genlm-latent production regime) and a per-step twist (ess>0) are handled
# identically to the slow path. There is deliberately NO critic-category gate
# (is_terminal_only is not consulted): a critic is just a potential, scored the
# same way regardless of where the rollout logits came from.


def test_terminal_critic_burst_vs_slow(llm):
    """DirectTokenSampler(llm) + a terminal indicator critic at ess=0 -- the genlm-latent
    production regime: rollouts drawn from the backend, indicator applied once at
    termination. No resampling; burst-vs-original log_ml unbiased across seeds."""
    _nobias("terminal-critic", llm, ml_floor=0.3, ml_k=2.0)


def test_twisting_critic_burst_vs_slow(llm):
    """DirectTokenSampler(llm) + a soft content-dependent critic at ess=0.5 -- the per-step
    twist regime. Exercises untwist/twist accumulation + ESS resampling on TWISTED weights;
    asserts the resample path fired and burst-vs-original log_ml + length are unbiased."""
    _nobias("twist-critic", llm, ml_floor=0.3, ml_k=2.5,
            len_bound=0.5, len_k=2.5, need_resample=True)


# ----- gate 2e: forward-free gate (an LM critic must NOT burst) ---------------
#
# A CPU critic is fine in a burst (the cases above). An LM critic is a non-injected
# forward inside the burst -- on the same engine it would reenter run_burst's step
# (deadlock); with the hop deleted there is nothing to even attempt it. The gate must
# route such a config off the fast lane.


def test_lm_critic_routed_to_slow_lane(llm):
    """An LM critic (a second PromptedLLM on the SAME engine) would forward inside the
    burst. The forward-free gate must catch it: burst_blocker gives a reason, and
    accelerate="require" raises instead of bursting."""
    from genlm.control.sampler.burst import NotAcceleratable, BlockReason

    def make():
        return DirectTokenSampler(llm)

    lm_critic = PromptedLLM(llm.model, eos_byte_strings=EOS_BYTES)
    reason = burst_blocker(_controller(make, 8, 0.0, 8, make_critic=lambda: lm_critic))
    assert reason is not None and reason.reason is BlockReason.FORWARD_NOT_INJECTABLE, reason

    llm.set_prompt_from_str(PROMPT)
    seed_all(SEED)
    with pytest.raises(NotAcceleratable):
        asyncio.run(make().smc(8, 0.0, 8, critic=lm_critic, accelerate="require"))


# ----- gate 2g: multi-view (proposal q + prior p0, two views on one engine) -------
#
# K=2 multi-view: DirectTokenSampler(potential=p0, proposal=q) where q and p0 are two
# PromptedLLMs on the SAME engine (here differing by prompt; the LoRA case differs by
# adapter -- same control path). The burst submits 2 substreams/particle, injects both
# warm logit views, draws from q and reweights by p0/q, fans the one drawn token to both
# substreams (lock-step). No cached original reference (and no main checkout) for this
# config, so compare against StepLoop (gate-1-pinned == original).


def test_multiview_proposal_burst_vs_steploop(llm):
    """Two prompt-views q/p0 on one engine -> K=2 multi-view burst; unbiased log_ml vs
    StepLoop across seeds (warm-KV residual only). Exercises the multi-view machinery:
    K substreams, K injected views, p0/q reweight, lock-step token fan-out."""
    base = llm.model
    q_ids = base.tokenizer.encode("Once upon a")
    p0_ids = base.tokenizer.encode(PROMPT)

    def make():
        q = PromptedLLM(base, prompt_ids=q_ids, eos_byte_strings=EOS_BYTES)
        p0 = PromptedLLM(base, prompt_ids=p0_ids, eos_byte_strings=EOS_BYTES)
        return DirectTokenSampler(potential=p0, proposal=q)

    assert can_burst(_controller(make, 8, 0.0, 10))  # K=2 multi-view rides the fast lane

    # The K=2 multiview log_ml estimator is high-variance: a flat proposal ("Once upon a")
    # makes the burst's warm-KV draws diverge from StepLoop on many tokens, and N=8 marginal
    # likelihood swings hard per seed (range ~+-10). The burst is unbiased over the seeds
    # (mean ~0), but a 6-seed mean is brittle -- a tiny draw change tips it past 2.5*sem.
    # Average over enough seeds that the unbiasedness check is robust (and more sensitive to
    # a real bias, not less).
    seeds = tuple(range(24))
    diffs, n_bursts = [], 0
    for seed in seeds:
        slow = _run_steploop(make, 8, 0.0, 10, seed)
        burst = _run_burst(make, 8, 0.0, 10, seed)
        s = _compare("multiview-q/p0", 0.0, 8, slow, burst)
        diffs.append(s["log_ml_diff"])
        n_bursts = max(n_bursts, s["n_bursts"])
    diffs = np.array(diffs)
    sem = diffs.std() / np.sqrt(len(diffs))
    print(
        f"\nmultiview q/p0 over {len(seeds)} seeds: "
        f"log_ml diff mean={diffs.mean():+.4f} sem={sem:.4f}"
    )
    assert n_bursts > 0, "multi-view config did not burst (n_bursts == 0)"
    assert abs(diffs.mean()) <= max(0.3, 2.5 * sem), (
        f"multiview burst log_ml biased: mean {diffs.mean():+.4f} (sem {sem:.4f})"
    )


def test_batched_multiview_burst_unbiased(llm):
    """B>1 groups, each a K=2 multi-view (q proposal + p0 prior, group-specific prompts)
    -> ONE batched burst over B x K substreams per particle. Per-group log_ml unbiased
    vs a single-run StepLoop of each group: group and view are orthogonal, so there is
    no cross-group coupling. ``accelerate="require"`` forces the batched multi-view
    burst (raises if the B>1 x K>1 gate wrongly rejects it)."""
    from genlm.control.sampler.sequence import SMC

    base = llm.model
    prompts = ["The", "Once upon a", "In the", "A B C", "Hello world", "To be"]
    B = len(prompts)

    def make_group(p):
        q = PromptedLLM(
            base, prompt_ids=base.tokenizer.encode(p + " then"), eos_byte_strings=EOS_BYTES
        )
        p0 = PromptedLLM(
            base, prompt_ids=base.tokenizer.encode(p), eos_byte_strings=EOS_BYTES
        )
        return DirectTokenSampler(potential=p0, proposal=q)

    refs = np.array(
        [_run_steploop(lambda pp=p: make_group(pp), 8, 0.0, 10, SEED)["log_ml"] for p in prompts]
    )

    seed_all(SEED)
    smcs = [SMC(make_group(p)) for p in prompts]
    seqs = asyncio.run(
        SMC.batched(
            smcs, n_particles=8, ess_threshold=0.0,
            max_tokens=10, accelerate="require",
        )
    )
    assert len(seqs) == B, f"SMC.batched returned {len(seqs)} groups, expected {B}"

    burst = np.array([s.log_ml for s in seqs])
    fb, fr = burst[np.isfinite(burst)], refs[np.isfinite(refs)]
    diff = fb.mean() - fr.mean()
    sem = np.sqrt(fb.std() ** 2 / max(len(fb), 1) + fr.std() ** 2 / max(len(fr), 1))
    print(
        f"\nbatched multiview B={B} K=2: burst mean={fb.mean():+.4f} "
        f"ref mean={fr.mean():+.4f} diff={diff:+.4f} sem={sem:.4f}"
    )
    assert abs(diff) <= max(0.3, 3.0 * sem), (
        f"batched multiview log_ml biased vs single-run StepLoop: diff {diff:+.4f} (sem {sem:.4f})"
    )


# ----- gate 2f: MultiTokenUnitSampler (synchronized unit-grain burst) ---------
#
# The unit grain is the one NON-free-running burst: a unit spans a VARIABLE number
# of subunit decode steps, so rows reach their unit boundary at different engine
# steps. Each row pops out and waits at its boundary; the controller runs exactly
# ONE unit round per burst and tests ESS once at the synced boundary -- the slow
# per-unit loop's timing. The byte-length boundary below makes units variable-
# length (Token is a bytes subclass), so the staggered pop-out is actually exercised
# (a fixed-length boundary would complete every row at the same step and hide it).


def test_multitoken_burst_vs_slow(llm):
    """MultiToken with a CONSTRAINED Direct subunit (``llm * coerced BoolFSA``) at ess=0.5:
    subunits ride the warm-KV fast lane with the boolfsa factor advancing per subunit; a
    unit completes at a byte-length boundary (variable length -> staggered pop-out); ESS
    fires once per unit round at the synced boundary. The constraint makes per-step weights
    NON-TRIVIAL, so the no-bias log_ml + length checks exercise per-unit weight accumulation
    + ESS + resample; ``need_rounds`` confirms the per-unit loop ran (>1 unit round)."""
    _nobias("multitoken-boolfsa[a-z ]+", llm, ml_floor=0.3, ml_k=2.5,
            len_bound=0.5, len_k=2.5, need_rounds=True)


def test_multitoken_multiview_burst_vs_steploop(llm):
    """Unit grain x multi-view: MultiToken over a K=2 subunit (DirectTokenSampler with
    q proposal + p0 prior, differing by prompt). ``burst_draw_sampler`` surfaces the
    subunit's two views, so the synchronized unit burst injects both per particle and
    draws subunits from q reweighted by p0/q. Unbiased log_ml vs StepLoop across seeds
    -- group/view/grain all compose."""
    base = llm.model
    q_ids = base.tokenizer.encode("Once upon a")
    p0_ids = base.tokenizer.encode(PROMPT)

    def make():
        q = PromptedLLM(base, prompt_ids=q_ids, eos_byte_strings=EOS_BYTES)
        p0 = PromptedLLM(base, prompt_ids=p0_ids, eos_byte_strings=EOS_BYTES)
        return MultiTokenUnitSampler(
            subunit_sampler=DirectTokenSampler(potential=p0, proposal=q),
            boundary_predicate=ByteLengthBoundary(3),
        )

    assert can_burst(_controller(make, 8, 0.5, 6))  # unit-grain multi-view fast lane

    seeds = (1234, 7, 99, 2024, 555, 31)
    diffs, n_bursts = [], 0
    for seed in seeds:
        slow = _run_steploop(make, 8, 0.5, 6, seed)
        burst = _run_burst(make, 8, 0.5, 6, seed)
        s = _compare("multitoken-multiview", 0.5, 8, slow, burst)
        diffs.append(s["log_ml_diff"])
        n_bursts = max(n_bursts, s["n_bursts"])
    diffs = np.array(diffs)
    sem = diffs.std() / np.sqrt(len(diffs))
    print(
        f"\nmultitoken multiview over {len(seeds)} seeds: "
        f"log_ml diff mean={diffs.mean():+.4f} sem={sem:.4f}"
    )
    assert n_bursts > 0, "multitoken multiview did not burst"
    assert abs(diffs.mean()) <= max(0.3, 2.5 * sem), (
        f"multitoken multiview burst log_ml biased: mean {diffs.mean():+.4f} (sem {sem:.4f})"
    )


# ----- gate 2e: SetTokenSampler (trie set construction over warm-KV iter weights) ----


def test_set_sampler_burst_vs_slow(llm):
    """SetTokenSampler burst vs the cached ORIGINAL (the async-trie set draw over the hop),
    unbiased log_ml across seeds. Comparing to the original (not our StepLoop) is the
    stronger anchor here -- SetTokenSampler has no byte-exact gate-1 pinning, so a Set-draw
    bug shared by both lanes would be invisible against StepLoop. Fresh EagerSetSampler per
    run (its trie task binds to that run's loop) is handled by the CASES factory."""
    _nobias("set[a-z ]+", llm, ml_floor=0.3, ml_k=2.5)


# ----- gate 2h: SMC.batched (B groups, ONE batched engine burst) --------------
#
# SMC.batched runs B examples as ONE population (B groups of n_particles), drawn
# through a SINGLE engine forward over all B*N rows; ESS / resample / log_ml are
# group-local. So each group must be statistically identical to running it alone --
# which is exactly the cached single-run references. We therefore REUSE the
# Checked against the EXACT batched path (StepLoop) at the SAME seed, paired -- like
# every other gate-2 test. Pairing is RNG-matched (both lanes draw all groups under the
# same shared stream in the same order), so MC variance cancels and only the warm-KV
# residual remains; a burst-specific B>1 bug shows as a persistent same-sign group-mean
# gap. (Comparing the batched group-mean against the cached SINGLE-run references is the
# wrong gauge: those are 12 high-variance short-sequence runs whose mean sits ~1 log_ml
# off the true value, so the difference is dominated by reference noise, not bias. The
# batched MATH itself -- B groups in one population == B solo runs, no cross-group
# coupling -- is gate-1's byte-exact per-group pinning, not this test's job.)


def test_batched_smc_burst_unbiased(llm):
    """B homogeneous groups in one batched engine burst vs the exact batched path.
    ``accelerate="require"`` forces the batched burst (raises if the batch isn't
    burst-homogeneous); ``"off"`` is the byte-exact StepLoop over the same B groups.
    Each pop-seed gives one paired group-mean log_ml diff; the mean across seeds is
    unbiased (~0). A persistent same-sign gap is a burst bug."""
    from genlm.control.sampler.sequence import SMC

    llm.set_prompt_from_str(PROMPT)
    target = boolfsa(llm, r"[aeiou ]+")
    pop_seeds = (1234, 7, 99, 2024, 555, 31, 808, 42, 17, 6, 71, 900)
    B = len(pop_seeds)

    def group_mean(seed, accelerate):
        seed_all(seed)
        smcs = [SMC(DirectTokenSampler(target)) for _ in range(B)]
        seqs = asyncio.run(
            SMC.batched(
                smcs, n_particles=16, ess_threshold=0.5,
                max_tokens=10, accelerate=accelerate,
            )
        )
        assert len(seqs) == B, f"SMC.batched returned {len(seqs)} groups, expected {B}"
        mls = np.array([s.log_ml for s in seqs])
        return mls[np.isfinite(mls)].mean()

    diffs = []
    for s in pop_seeds:
        t0 = time.perf_counter()
        burst = group_mean(s, "require")
        slow = group_mean(s, "off")
        diffs.append(burst - slow)
        _log(
            f"SMC.batched B={B} seed={s}: {time.perf_counter() - t0:.1f}s  "
            f"burst group-mean={burst:+.4f} slow={slow:+.4f} diff={burst - slow:+.4f}"
        )
    diffs = np.array(diffs)
    sem = diffs.std() / np.sqrt(len(diffs))
    _log(
        f"SMC.batched burst-vs-StepLoop (paired): group-mean log_ml diff "
        f"mean={diffs.mean():+.4f} sem={sem:.4f}"
    )
    assert abs(diffs.mean()) <= max(0.4, 3.0 * sem), (
        f"batched burst group-mean log_ml biased vs the exact batched path: "
        f"mean diff {diffs.mean():+.4f} (sem {sem:.4f})"
    )
