"""Gate-2 on vLLM: SMC served by the vLLM engine is UNBIASED vs the same cases served by
plain per-context forwards.

Byte-exactness is impossible here -- the engine reads warm-KV decode logits instead of
re-prefilling every step, a ~1e-2/logit residual that may flip a Gumbel-max draw -- so each
test averages the run-vs-reference log_ml (and length) diff across seeds and asserts the
MEAN sits within sampling noise of 0 (``_harness.assert_unbiased``). A consistent same-sign
gap is a BUG, not a tolerance.

Two cached references, chosen per case (the ``reference`` field of ``gate2_cases.CASES``):
- ``"forward_cached"`` -- plain per-context forwards under the counter-based picker, cached
  in ``gate2_forward_snapshot.json`` by ``gen_reference.py``. RNG-matched to this run, so
  the paired diff is tight (engine numeric residual only).
- ``"ref"`` -- the genuine ORIGINAL genlm-control (main + llamppl ``smc_standard``), cached
  in ``gate2_snapshot.json`` by ``gen_original_reference.py``. The independent anchor.
Any other value resolves live over ``ref_llm``, a second backend. A missing cached key is a
hard error (run the generator) -- never a silent self-comparison.

Config (seeds/N/ess/critics/samplers) and the shared critics live in ``gate2_cases.py``,
imported by BOTH this gate and the generators so they cannot drift; the seed/serialization/
no-bias-assert harness is ``_harness.py`` (shared with gate-1).

**Regenerate the cached original** (after changing a ``"ref"`` config) on the box, shadowing
our genlm.control with main's::

    PYTHONPATH=/root/genlm/genlm-control-main VLLM_USE_FLASHINFER_SAMPLER=0 \\
        /root/genlm-venv/bin/python tests/sampler/gen_original_reference.py

Requires CUDA + vLLM; uses gpt2. Run on the box with ``VLLM_USE_FLASHINFER_SAMPLER=0``.
"""

import asyncio
import os
import time

import numpy as np
import pytest

torch = pytest.importorskip("torch")
if not torch.cuda.is_available():  # pragma: no cover
    pytest.skip("engine-native parity needs CUDA + vLLM", allow_module_level=True)

from genlm.control.potential.built_in.llm import PromptedLLM  # noqa: E402
from genlm.control.sampler.token import DirectTokenSampler  # noqa: E402
from genlm.control.potential.coerce import Coerced  # noqa: E402
from genlm.control.sampler.unit import MultiTokenUnitSampler  # noqa: E402
from genlm.control.util import flatten_units  # noqa: E402

from _harness import (  # noqa: E402
    seed_all,
    load_snapshot,
    log,
    assert_case_unbiased,
    live_ref_factory,
    run_case,
    compare_runs,
    threefry_draw,  # noqa: F401 -- autouse fixture, armed by importing it
)
from gate2_cases import (  # noqa: E402
    CASES,
    MODEL,
    PROMPT,
    EOS_BYTES,
    CONFIG,
    ByteLengthBoundary,
    boolfsa,
)

SEED = 1234  # single-seed default (unconstrained); per-case seeds come from CASES

# Original-reference snapshot (model/prompt/eos in CONFIG, enforced on load). Generated by
# ``gen_original_reference.py`` from the ORIGINAL genlm-control; this gate only LOADS it.
_SNAPSHOT_PATH = os.path.join(os.path.dirname(__file__), "gate2_snapshot.json")
try:
    _SNAPSHOT = load_snapshot(_SNAPSHOT_PATH, CONFIG)
except FileNotFoundError:  # pragma: no cover
    _SNAPSHOT = {}

# Tight reference: cached plain-forward+threefry (RNG-matched to this run), generated by
# ``gen_reference.py``. SEPARATE file from the original ``_SNAPSHOT`` above.
_FORWARD_PATH = os.path.join(os.path.dirname(__file__), "gate2_forward_snapshot.json")
try:
    _FORWARD_SNAP = load_snapshot(_FORWARD_PATH, CONFIG)
except FileNotFoundError:  # pragma: no cover
    _FORWARD_SNAP = {}


def _key(label, n_particles, ess_threshold, max_tokens, seed):
    return f"{label}|N={n_particles}|ess={ess_threshold}|mt={max_tokens}|seed={seed}"


def _ref(label, n_particles, ess_threshold, max_tokens, seed):
    """Load the cached ORIGINAL genlm-control reference for this config. A missing
    key is a hard error (run ``gen_original_reference.py`` on the box) rather than a
    silent self-comparison."""
    key = _key(label, n_particles, ess_threshold, max_tokens, seed)
    if key not in _SNAPSHOT:  # pragma: no cover
        raise RuntimeError(
            f"no cached original reference for {key!r}; regenerate with "
            "gen_original_reference.py (PYTHONPATH=.../genlm-control-main)"
        )
    return _SNAPSHOT[key]


def _forward_cached(label, n_particles, ess_threshold, max_tokens, seed):
    """Load the cached plain-forward+threefry (tight, RNG-matched) reference. A missing key
    is a hard error -- run ``gen_reference.py``."""
    key = _key(label, n_particles, ess_threshold, max_tokens, seed)
    if key not in _FORWARD_SNAP:  # pragma: no cover
        raise RuntimeError(
            f"no cached plain-forward reference for {key!r}; regenerate with "
            "gen_reference.py"
        )
    return _FORWARD_SNAP[key]


@pytest.fixture(scope="module")
def llm():
    from genlm.backend.llm import AsyncVirtualLM

    # Under xdist, stagger engine init by worker so simultaneous vLLM memory-profiles
    # don't race for GPU memory (each worker reserves gpu_memory_utilization on its own).
    wid = os.environ.get("PYTEST_XDIST_WORKER")
    if wid:
        time.sleep(int(wid[2:]) * 10)
    log(f"loading {MODEL} vLLM engine ...")
    t0 = time.perf_counter()
    model = AsyncVirtualLM.from_name(
        MODEL,
        engine_opts={
            "gpu_memory_utilization": 0.2,
            "max_model_len": 256,
            "enable_prefix_caching": True,
            "enforce_eager": True,  # skip CUDA-graph capture -> faster startup for tests
        },
    )
    log(f"engine ready in {time.perf_counter() - t0:.1f}s")
    return PromptedLLM(model, eos_byte_strings=EOS_BYTES)


@pytest.fixture(scope="module")
def ref_llm():
    """The reference backend: the same model behind plain per-context forwards, so a
    comparison against it measures engine serving and nothing else."""
    from genlm.backend.llm import AsyncTransformer

    ref = PromptedLLM(AsyncTransformer.from_name(MODEL), eos_byte_strings=EOS_BYTES)
    ref.set_prompt_from_str(PROMPT)
    return ref


def _resolve_ref(ref_llm):
    """This gate's reference per case: the cached plain-forward run where that is the
    anchor, the cached original where one exists, else a live run over ``ref_llm``."""
    live = live_ref_factory(ref_llm)

    def resolve(case, seed, make, mkc):
        if case.reference == "ref":
            return _ref(case.label, case.n_particles, case.ess, case.max_tokens, seed)
        if case.reference == "forward_cached":
            return _forward_cached(
                case.label, case.n_particles, case.ess, case.max_tokens, seed
            )
        return live(case, seed, make, mkc)

    return resolve


def _nobias(label, llm, ref_llm, **kwargs):
    """Drive a homogeneous CASES no-bias case against this gate's references."""
    return assert_case_unbiased(
        CASES[label], llm, PROMPT, _resolve_ref(ref_llm), **kwargs
    )


# ----- gate 2a: unconstrained (no-bias over seeds; the force-EOS boundary weight +
#       bf16 draw flips make a single-seed tight check invalid) ----------------------


def test_unconstrained_unbiased(llm, ref_llm):
    _nobias("unconstrained", llm, ref_llm, ml_floor=0.3, ml_k=2.5, len_bound=1.5)


# ----- gate 2b: constrained Direct (llm * boolfsa). Looser [a-z ]+ at ess=0 (no
#       resample); tighter [aeiou ]+ at ess=0.5 FORCES the resample path. --


def test_constrained_boolfsa_unbiased(llm, ref_llm):
    _nobias(
        "constrained-boolfsa[a-z ]+", llm, ref_llm, ml_floor=0.3, ml_k=2.5, len_bound=1.5
    )


def test_constrained_forces_resample_unbiased(llm, ref_llm):
    _nobias("boolfsa[aeiou ]+", llm, ref_llm, ml_floor=0.3, ml_k=2.0, len_bound=1.5,
            need_resample=True)


# ----- gate 2c: AWRS (rejection over engine logits + stateful condition; per-seed rng) --


def test_awrs_unbiased(llm, ref_llm):
    _nobias("awrs[a-z ]+", llm, ref_llm, ml_floor=0.3, ml_k=2.0, len_bound=1.5)


# ----- gate 2d: critic (terminal reweight + per-step twist) -------------------
#
# The critic is NOT a sampler -- it reweights the population. There is deliberately NO
# critic-category gate: a critic is just a potential, scored the same way regardless of
# where the rollout logits came from.


def test_terminal_critic_unbiased(llm, ref_llm):
    """DirectTokenSampler(llm) + a terminal indicator critic at ess=0 -- the genlm-latent
    production regime: rollouts drawn from the backend, indicator applied once at
    termination. No resampling; log_ml unbiased across seeds."""
    _nobias("terminal-critic", llm, ref_llm, ml_floor=0.3, ml_k=2.0)


def test_terminal_critic_resample_unbiased(llm, ref_llm):
    """The same terminal critic at ess=0.5. A terminal critic forces `twist_with_critic`
    off, so this is the only config where a resample can cross a terminal score -- the
    score has to land before the ESS test that consumes it."""
    _nobias("terminal-critic-resample", llm, ref_llm, ml_floor=0.3, ml_k=2.0,
            need_resample=True)


def test_twisting_critic_unbiased(llm, ref_llm):
    """DirectTokenSampler(llm) + a soft content-dependent critic at ess=0.5 -- the per-step
    twist regime. Exercises untwist/twist accumulation + ESS resampling on TWISTED weights;
    asserts the resample path fired and that log_ml + length are unbiased."""
    _nobias("twist-critic", llm, ref_llm, ml_floor=0.3, ml_k=2.5,
            len_bound=0.5, len_k=2.5, need_resample=True)


# ----- gate 2e: LM critic (a critic whose leaf is the same engine as the sampler's) -----


def test_lm_critic_twist_token_unbiased(llm, ref_llm):
    """Token-grain LM critic (ess>0, free-running): the per-step twist and the terminal
    score both come off the same engine that serves the rollouts. Unbiased log_ml vs plain
    forwards across paired seeds.

    The critic runs under its OWN prompt, distinct from the sampler's: a
    critic-equals-target twist is the full sequence logp, which degenerates
    resampling to every step and makes the paired log_ml diff heavy-tailed
    (one near-tie draw flip -> tens of nats); a distinct critic keeps the twist
    moderate so the statistic converges."""
    def make(m):
        return DirectTokenSampler(m)

    def make_critic(m):
        # Distinct prompt (see docstring); also, an unprompted PromptedLLM sends
        # the empty-context prefix as an empty engine prompt (vLLM rejects it).
        return PromptedLLM(
            m.model,
            prompt_ids=m.model.tokenizer.encode("It is known that"),
            eos_byte_strings=EOS_BYTES,
        )

    llm.set_prompt_from_str(PROMPT)
    seeds = (1234, 7, 99, 2024, 555, 31, 42, 271, 828, 1618)
    diffs = []
    for seed in seeds:
        ref = run_case(
            lambda: make(ref_llm), 8, 0.5, 8, seed, lambda: make_critic(ref_llm)
        )
        run = run_case(lambda: make(llm), 8, 0.5, 8, seed, lambda: make_critic(llm))
        s = compare_runs("lm-critic-twist-token", 0.5, 8, ref, run)
        diffs.append(s["log_ml_diff"])
    diffs = np.array(diffs)
    sem = diffs.std() / np.sqrt(len(diffs))
    print(
        f"\nlm-critic token twist over {len(seeds)} seeds: "
        f"log_ml diff mean={diffs.mean():+.4f} sem={sem:.4f}"
    )
    assert abs(diffs.mean()) <= max(0.3, 2.5 * sem), (
        f"lm-critic token twist log_ml biased: mean {diffs.mean():+.4f} (sem {sem:.4f})"
    )


def test_lm_critic_terminal_unbiased(llm, ref_llm):
    """LM critic at ess=0 (the production E-step shape): the critic's LM leaf scores the
    completed sequences via batch_score. Unbiased log_ml vs plain forwards across paired
    seeds."""
    def make(m):
        return DirectTokenSampler(m)

    def make_critic(m):
        # The critic needs its own prompt: an unprompted PromptedLLM sends the
        # empty-context prefix as an empty engine prompt (vLLM rejects it).
        return PromptedLLM(
            m.model,
            prompt_ids=m.model.tokenizer.encode(PROMPT),
            eos_byte_strings=EOS_BYTES,
        )

    llm.set_prompt_from_str(PROMPT)
    seeds = (1234, 7, 99, 2024, 555, 31)
    diffs = []
    for seed in seeds:
        ref = run_case(
            lambda: make(ref_llm), 8, 0.0, 8, seed, lambda: make_critic(ref_llm)
        )
        run = run_case(lambda: make(llm), 8, 0.0, 8, seed, lambda: make_critic(llm))
        s = compare_runs("lm-critic-terminal", 0.0, 8, ref, run)
        diffs.append(s["log_ml_diff"])
    diffs = np.array(diffs)
    sem = diffs.std() / np.sqrt(len(diffs))
    print(
        f"\nlm-critic terminal over {len(seeds)} seeds: "
        f"log_ml diff mean={diffs.mean():+.4f} sem={sem:.4f}"
    )
    assert abs(diffs.mean()) <= max(0.3, 2.5 * sem), (
        f"lm-critic terminal log_ml biased: mean {diffs.mean():+.4f} (sem {sem:.4f})"
    )


def test_lm_critic_twist_unit_unbiased(llm, ref_llm):
    """LM critic at ess=0.5 over UNIT grain: the critic scores whole units, so its
    per-token logp sums have to accumulate across a unit's subunits. Unbiased log_ml vs
    plain forwards across paired seeds."""
    def make(m):
        return MultiTokenUnitSampler(
            subunit_sampler=DirectTokenSampler(m),
            boundary_predicate=ByteLengthBoundary(3),
        )

    def make_critic(m):
        # Unit-grain contexts hold nested units, so the token-level critic is
        # coerced through flatten_units (the standard unit-critic pattern; a bare
        # PromptedLLM would choke on list items). Its own prompt is required: an
        # unprompted critic sends the empty-context prefix as an empty engine
        # prompt (vLLM rejects it).
        lm = PromptedLLM(
            m.model,
            prompt_ids=m.model.tokenizer.encode(PROMPT),
            eos_byte_strings=EOS_BYTES,
        )
        return Coerced(lm, lm.vocab, f=flatten_units, prune=False)

    llm.set_prompt_from_str(PROMPT)
    seeds = (1234, 7, 99, 2024, 555, 31)
    diffs = []
    for seed in seeds:
        ref = run_case(
            lambda: make(ref_llm), 8, 0.5, 6, seed, lambda: make_critic(ref_llm)
        )
        run = run_case(lambda: make(llm), 8, 0.5, 6, seed, lambda: make_critic(llm))
        s = compare_runs("lm-critic-twist-unit", 0.5, 8, ref, run)
        diffs.append(s["log_ml_diff"])
    diffs = np.array(diffs)
    sem = diffs.std() / np.sqrt(len(diffs))
    print(
        f"\nlm-critic unit twist over {len(seeds)} seeds: "
        f"log_ml diff mean={diffs.mean():+.4f} sem={sem:.4f}"
    )
    assert abs(diffs.mean()) <= max(0.3, 2.5 * sem), (
        f"lm-critic unit twist log_ml biased: mean {diffs.mean():+.4f} (sem {sem:.4f})"
    )


# ----- gate 2g: multi-view (proposal q + prior p0, two views on one engine) -------
#
# K=2 multi-view: DirectTokenSampler(potential=p0, proposal=q) where q and p0 are two
# PromptedLLMs on the SAME engine (here differing by prompt; the LoRA case differs by
# adapter -- same control path). Draws come from q and are reweighted by p0/q.


def test_multiview_proposal_unbiased(llm, ref_llm):
    """Two prompt-views q/p0 on one engine -> K=2 multi-view; unbiased log_ml vs plain
    forwards across seeds. Exercises the multi-view machinery: two logit views per step,
    p0/q reweight, one drawn token advancing both."""
    def make(m):
        q = PromptedLLM(
            m.model,
            prompt_ids=m.model.tokenizer.encode("Once upon a"),
            eos_byte_strings=EOS_BYTES,
        )
        p0 = PromptedLLM(
            m.model,
            prompt_ids=m.model.tokenizer.encode(PROMPT),
            eos_byte_strings=EOS_BYTES,
        )
        return DirectTokenSampler(potential=p0, proposal=q)

    # The K=2 multiview log_ml estimator is high-variance: a flat proposal ("Once upon a")
    # makes the engine's draws diverge from the reference's on many tokens, and N=8 marginal
    # likelihood swings hard per seed (range ~+-10). The run is unbiased over the seeds
    # (mean ~0), but a 6-seed mean is brittle -- a tiny draw change tips it past 2.5*sem.
    # Average over enough seeds that the unbiasedness check is robust (and more sensitive to
    # a real bias, not less).
    seeds = tuple(range(24))
    diffs = []
    for seed in seeds:
        ref = run_case(lambda: make(ref_llm), 8, 0.0, 10, seed)
        run = run_case(lambda: make(llm), 8, 0.0, 10, seed)
        s = compare_runs("multiview-q/p0", 0.0, 8, ref, run)
        diffs.append(s["log_ml_diff"])
    diffs = np.array(diffs)
    sem = diffs.std() / np.sqrt(len(diffs))
    print(
        f"\nmultiview q/p0 over {len(seeds)} seeds: "
        f"log_ml diff mean={diffs.mean():+.4f} sem={sem:.4f}"
    )
    assert abs(diffs.mean()) <= max(0.3, 2.5 * sem), (
        f"multiview log_ml biased: mean {diffs.mean():+.4f} (sem {sem:.4f})"
    )


def test_batched_multiview_unbiased(llm, ref_llm):
    """B>1 groups, each a K=2 multi-view (q proposal + p0 prior, group-specific prompts),
    run as ONE batched population. Per-group log_ml unbiased vs a single-run plain-forward
    reference of each group: group and view are orthogonal, so there is no cross-group
    coupling."""
    from genlm.control.sampler.sequence import SMC

    prompts = ["The", "Once upon a", "In the", "A B C", "Hello world", "To be"]
    B = len(prompts)

    def make_group(m, p):
        q = PromptedLLM(
            m.model,
            prompt_ids=m.model.tokenizer.encode(p + " then"),
            eos_byte_strings=EOS_BYTES,
        )
        p0 = PromptedLLM(
            m.model, prompt_ids=m.model.tokenizer.encode(p), eos_byte_strings=EOS_BYTES
        )
        return DirectTokenSampler(potential=p0, proposal=q)

    refs = np.array(
        [
            run_case(lambda pp=p: make_group(ref_llm, pp), 8, 0.0, 10, SEED)["log_ml"]
            for p in prompts
        ]
    )

    seed_all(SEED)
    smcs = [SMC(make_group(llm, p)) for p in prompts]
    seqs = asyncio.run(
        SMC.batched(smcs, n_particles=8, ess_threshold=0.0, max_tokens=10)
    )
    assert len(seqs) == B, f"SMC.batched returned {len(seqs)} groups, expected {B}"

    run = np.array([s.log_ml for s in seqs])
    fb, fr = run[np.isfinite(run)], refs[np.isfinite(refs)]
    diff = fb.mean() - fr.mean()
    sem = np.sqrt(fb.std() ** 2 / max(len(fb), 1) + fr.std() ** 2 / max(len(fr), 1))
    print(
        f"\nbatched multiview B={B} K=2: run mean={fb.mean():+.4f} "
        f"ref mean={fr.mean():+.4f} diff={diff:+.4f} sem={sem:.4f}"
    )
    assert abs(diff) <= max(0.3, 3.0 * sem), (
        f"batched multiview log_ml biased vs single-run forwards: "
        f"diff {diff:+.4f} (sem {sem:.4f})"
    )


# ----- gate 2f: MultiTokenUnitSampler (unit grain) ---------------------------
#
# A unit spans a VARIABLE number of subunit steps, so rows reach their unit boundary at
# different step counts; ESS is tested once per unit round, at the synced boundary. The
# byte-length boundary below makes units variable-length (Token is a bytes subclass), so
# the stagger is actually exercised (a fixed-length boundary would hide it).


def test_multitoken_unbiased(llm, ref_llm):
    """MultiToken with a CONSTRAINED Direct subunit (``llm * coerced BoolFSA``) at ess=0.5:
    the boolfsa factor advances per subunit, a unit completes at a byte-length boundary
    (variable length -> staggered boundaries), and ESS fires once per unit round. The
    constraint makes per-step weights NON-TRIVIAL, so the no-bias log_ml + length checks
    exercise per-unit weight accumulation + ESS + resample."""
    _nobias("multitoken-boolfsa[a-z ]+", llm, ref_llm, ml_floor=0.3, ml_k=2.5,
            len_bound=0.5, len_k=2.5)


def test_multitoken_multiview_unbiased(llm, ref_llm):
    """Unit grain x multi-view: MultiToken over a K=2 subunit (DirectTokenSampler with
    q proposal + p0 prior, differing by prompt). Unbiased log_ml vs plain forwards across
    seeds -- group/view/grain all compose."""
    def make(m):
        q = PromptedLLM(
            m.model,
            prompt_ids=m.model.tokenizer.encode("Once upon a"),
            eos_byte_strings=EOS_BYTES,
        )
        p0 = PromptedLLM(
            m.model,
            prompt_ids=m.model.tokenizer.encode(PROMPT),
            eos_byte_strings=EOS_BYTES,
        )
        return MultiTokenUnitSampler(
            subunit_sampler=DirectTokenSampler(potential=p0, proposal=q),
            boundary_predicate=ByteLengthBoundary(3),
        )

    seeds = (1234, 7, 99, 2024, 555, 31)
    diffs = []
    for seed in seeds:
        ref = run_case(lambda: make(ref_llm), 8, 0.5, 6, seed)
        run = run_case(lambda: make(llm), 8, 0.5, 6, seed)
        s = compare_runs("multitoken-multiview", 0.5, 8, ref, run)
        diffs.append(s["log_ml_diff"])
    diffs = np.array(diffs)
    sem = diffs.std() / np.sqrt(len(diffs))
    print(
        f"\nmultitoken multiview over {len(seeds)} seeds: "
        f"log_ml diff mean={diffs.mean():+.4f} sem={sem:.4f}"
    )
    assert abs(diffs.mean()) <= max(0.3, 2.5 * sem), (
        f"multitoken multiview log_ml biased: mean {diffs.mean():+.4f} (sem {sem:.4f})"
    )


# ----- gate 2e: SetTokenSampler (trie set construction over iter weights) ----


def test_set_sampler_unbiased(llm, ref_llm):
    """SetTokenSampler (the async-trie set draw) vs the cached ORIGINAL, unbiased log_ml
    across seeds. Comparing to the original is the stronger anchor here -- SetTokenSampler
    has no byte-exact gate-1 pinning, so a Set-draw bug shared by run and reference would
    be invisible otherwise. Fresh EagerSetSampler per run (its trie task binds to that
    run's loop) is handled by the CASES factory."""
    _nobias("set[a-z ]+", llm, ref_llm, ml_floor=0.3, ml_k=2.5)


# ----- gate 2h: SMC.batched (B groups in ONE population) ----------------------
#
# SMC.batched runs B examples as ONE population (B groups of n_particles); ESS / resample /
# log_ml are group-local, so each group must be statistically identical to running it alone.
# The comparison is paired at the same seed (both sides draw all groups under the same
# shared stream in the same order), so MC variance cancels and a B>1 bug shows as a
# persistent same-sign group-mean gap. (Comparing the batched group-mean against the cached
# SINGLE-run references is the wrong gauge: those are 12 high-variance short-sequence runs
# whose mean sits ~1 log_ml off the true value, so the difference is dominated by reference
# noise, not bias. The batched MATH itself -- B groups in one population == B solo runs, no
# cross-group coupling -- is gate-1's byte-exact per-group pinning, not this test's job.)


def test_batched_smc_unbiased(llm, ref_llm):
    """B homogeneous groups in one batched population, engine-served vs plain forwards.
    Each pop-seed gives one paired group-mean log_ml diff; the mean across seeds is
    unbiased (~0). A persistent same-sign gap is a bug."""
    from genlm.control.sampler.sequence import SMC

    llm.set_prompt_from_str(PROMPT)
    target = boolfsa(llm, r"[aeiou ]+")
    ref_target = boolfsa(ref_llm, r"[aeiou ]+")
    pop_seeds = (1234, 7, 99, 2024, 555, 31, 808, 42, 17, 6, 71, 900)
    B = len(pop_seeds)

    def group_mean(seed, tgt):
        seed_all(seed)
        smcs = [SMC(DirectTokenSampler(tgt)) for _ in range(B)]
        seqs = asyncio.run(
            SMC.batched(smcs, n_particles=16, ess_threshold=0.5, max_tokens=10)
        )
        assert len(seqs) == B, f"SMC.batched returned {len(seqs)} groups, expected {B}"
        mls = np.array([s.log_ml for s in seqs])
        return mls[np.isfinite(mls)].mean()

    diffs = []
    for s in pop_seeds:
        t0 = time.perf_counter()
        run = group_mean(s, target)
        ref = group_mean(s, ref_target)
        diffs.append(run - ref)
        log(
            f"SMC.batched B={B} seed={s}: {time.perf_counter() - t0:.1f}s  "
            f"run group-mean={run:+.4f} ref={ref:+.4f} diff={run - ref:+.4f}"
        )
    diffs = np.array(diffs)
    sem = diffs.std() / np.sqrt(len(diffs))
    log(
        f"SMC.batched run-vs-forwards (paired): group-mean log_ml diff "
        f"mean={diffs.mean():+.4f} sem={sem:.4f}"
    )
    assert abs(diffs.mean()) <= max(0.4, 3.0 * sem), (
        f"batched group-mean log_ml biased vs plain forwards: "
        f"mean diff {diffs.mean():+.4f} (sem {sem:.4f})"
    )


def test_batched_per_group_lm_critic_unbiased(llm, ref_llm):
    """B groups carrying DISTINCT token-grain LM critics (own prompt each). Every row must
    be scored by ITS group's critic, not group 0's. Group-mean log_ml stays unbiased vs
    plain forwards."""
    from genlm.control.sampler.sequence import SMC

    hints = ("It is known that", "Consider instead", "Recall the fact that")
    B = len(hints)
    seeds = (1234, 7, 99, 2024, 555, 31, 42, 271, 828, 1618,
             6, 71, 900, 17, 808, 2718, 3141, 5772, 88, 909)

    def make_critics(m):
        return [
            PromptedLLM(
                m.model,
                prompt_ids=m.model.tokenizer.encode(hint),
                eos_byte_strings=EOS_BYTES,
            )
            for hint in hints
        ]

    llm.set_prompt_from_str(PROMPT)
    critics = make_critics(llm)
    ref_critics = make_critics(ref_llm)

    def group_mean(seed, m, cs):
        seed_all(seed)
        smcs = [SMC(DirectTokenSampler(m), critic=c) for c in cs]
        seqs = asyncio.run(
            SMC.batched(smcs, n_particles=8, ess_threshold=0.5, max_tokens=8)
        )
        assert len(seqs) == B, f"SMC.batched returned {len(seqs)} groups, expected {B}"
        mls = np.array([s.log_ml for s in seqs])
        return mls[np.isfinite(mls)].mean()

    # An LM critic twist over a short horizon resamples hard, so a single paired diff
    # runs to several nats; the seed count is what makes the mean a usable statistic.
    diffs = []
    for s in seeds:
        t0 = time.perf_counter()
        run = group_mean(s, llm, critics)
        ref = group_mean(s, ref_llm, ref_critics)
        diffs.append(run - ref)
        log(
            f"per-group LM critic B={B} seed={s}: {time.perf_counter() - t0:.1f}s  "
            f"run group-mean={run:+.4f} ref={ref:+.4f} diff={run - ref:+.4f}"
        )
    diffs = np.array(diffs)
    sem = diffs.std() / np.sqrt(len(diffs))
    log(
        f"batched per-group LM critic (paired): group-mean log_ml diff "
        f"mean={diffs.mean():+.4f} sem={sem:.4f}"
    )
    assert abs(diffs.mean()) <= max(0.4, 3.0 * sem), (
        f"per-group LM critic group-mean log_ml biased: "
        f"mean diff {diffs.mean():+.4f} (sem {sem:.4f})"
    )
