coverage:
  status:
    project:
      default:
        target: auto           # auto = compare to base branch
        threshold: 1.0         # allow up to 1% drop in total project coverage
        informational: false   # fail the PR if threshold is exceeded
    patch:
      default:
        target: auto
        threshold: 1.0         # allow up to 1% drop in coverage on changed lines
        informational: false
